# Generated by Django 3.2.9 on 2022-09-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_phone_no_verified',
            field=models.BooleanField(default=True, verbose_name='Is Phone Number Verified'),
        ),
    ]
